
[crop]
	#True to enable the crop, false to disable it
	elemental = true
	#True to enable the crop, false to disable it
	emerald = true
	#True to enable the crop, false to disable it
	clay = true
	#True to enable the crop, false to disable it
	glowstone = true
	#True to enable the crop, false to disable it
	quartz = true
	#True to enable the crop, false to disable it
	shard = true
	#True to enable the crop, false to disable it
	crystal = true
	#True to enable the crop, false to disable it
	ender = true
	#True to enable the crop, false to disable it
	bone = true
	#True to enable the crop, false to disable it
	eye = true
	#True to enable the crop, false to disable it
	powder = true
	#True to enable the crop, false to disable it
	paper = true
	#True to enable the crop, false to disable it
	sugar = true
	#True to enable the crop, false to disable it
	charcoal = true
	#True to enable the crop, false to disable it
	flint = true
	#True to enable the crop, false to disable it
	snowball = true
	#True to enable the crop, false to disable it
	firework = true
	#True to enable the crop, false to disable it
	nether = true
	#True to enable the crop, false to disable it
	bottle = true
	#True to enable the crop, false to disable it
	foot = true
	#True to enable the crop, false to disable it
	hide = true
	#True to enable the crop, false to disable it
	leather = true
	#True to enable the crop, false to disable it
	feather = true
	#True to enable the crop, false to disable it
	blaze = true
	#True to enable the crop, false to disable it
	ghast = true
	#True to enable the crop, false to disable it
	magma = true
	#True to enable the crop, false to disable it
	shell = true
	#True to enable the crop, false to disable it
	star = true
	#True to enable the crop, false to disable it
	string = true
	#True to enable the crop, false to disable it
	slime = true
	#True to enable the crop, false to disable it
	zombie = true
	#True to enable the crop, false to disable it
	vine = true
	#True to enable the crop, false to disable it
	lilypad = true
	#True to enable the crop, false to disable it
	bush = true
	#True to enable the crop, false to disable it
	grass = true
	#True to enable the crop, false to disable it
	largefern = true
	#True to enable the crop, false to disable it
	tallgrass = true
	#True to enable the crop, false to disable it
	fern = true
	#True to enable the crop, false to disable it
	oak = true
	#True to enable the crop, false to disable it
	spruce = true
	#True to enable the crop, false to disable it
	birch = true
	#True to enable the crop, false to disable it
	jungle = true
	#True to enable the crop, false to disable it
	acacia = true
	#True to enable the crop, false to disable it
	darkoak = true
	#True to enable the crop, false to disable it
	apple = true
	#True to enable the crop, false to disable it
	goldenapple = true
	#True to enable the crop, false to disable it
	bread = true
	#True to enable the crop, false to disable it
	egg = true
	#True to enable the crop, false to disable it
	clownfish = true
	#True to enable the crop, false to disable it
	pufferfish = true
	#True to enable the crop, false to disable it
	cookie = true
	#True to enable the crop, false to disable it
	chorus = true
	#True to enable the crop, false to disable it
	rawbeef = true
	#True to enable the crop, false to disable it
	rawporc = true
	#True to enable the crop, false to disable it
	fish = true
	#True to enable the crop, false to disable it
	salmon = true
	#True to enable the crop, false to disable it
	rawchicken = true
	#True to enable the crop, false to disable it
	rawrabbit = true
	#True to enable the crop, false to disable it
	rawmutton = true
	#True to enable the crop, false to disable it
	orange = true
	#True to enable the crop, false to disable it
	magenta = true
	#True to enable the crop, false to disable it
	lightblue = true
	#True to enable the crop, false to disable it
	yellow = true
	#True to enable the crop, false to disable it
	lime = true
	#True to enable the crop, false to disable it
	pink = true
	#True to enable the crop, false to disable it
	gray = true
	#True to enable the crop, false to disable it
	silver = true
	#True to enable the crop, false to disable it
	cyan = true
	#True to enable the crop, false to disable it
	purple = true
	#True to enable the crop, false to disable it
	brown = true
	#True to enable the crop, false to disable it
	green = true
	#True to enable the crop, false to disable it
	red = true
	#True to enable the crop, false to disable it
	black = true
	#True to enable the crop, false to disable it
	totem = true
	#True to enable the crop, false to disable it
	lead2 = true
	#True to enable the crop, false to disable it
	nametag = true
	#True to enable the crop, false to disable it
	xp = true
	#True to enable the crop, false to disable it
	sea = true
	#True to enable the crop, false to disable it
	scute = true
	#True to enable the crop, false to disable it
	nautilus = true
	#True to enable the crop, false to disable it
	phantom = true
	#True to enable the crop, false to disable it
	wither = true
	#True to enable the crop, false to disable it
	dragon = true
	#True to enable the crop, false to disable it
	blue = true
	#True to enable the crop, false to disable it
	ink = true
	#True to enable the crop, false to disable it
	white = true
	#True to enable the crop, false to disable it
	honeycomb = true
	#True to enable the crop, false to disable it
	netherite = true
	#True to enable the crop, false to disable it
	glowink = true
	#True to enable the crop, false to disable it
	copper = true
	#True to enable the crop, false to disable it
	amethyst = true

[cropChance]
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	elemental = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	coal = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	iron = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	gold = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	lapis = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	redstone = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	diamond = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	emerald = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	clay = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	glowstone = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	quartz = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	shard = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	crystal = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	ender = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	bone = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	eye = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	powder = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	paper = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	sugar = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	charcoal = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	flint = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	snowball = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	firework = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	nether = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	bottle = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	foot = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	hide = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	leather = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	feather = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	blaze = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	ghast = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	magma = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	shell = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	star = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	string = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	slime = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	zombie = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	vine = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	lilypad = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	bush = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	grass = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	largefern = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	tallgrass = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	fern = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	oak = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	spruce = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	birch = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	jungle = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	acacia = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	darkoak = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	apple = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	goldenapple = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	bread = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	egg = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	clownfish = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	pufferfish = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	cookie = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	chorus = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	rawbeef = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	rawporc = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	fish = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	salmon = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	rawchicken = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	rawrabbit = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	rawmutton = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	orange = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	magenta = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	lightblue = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	yellow = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	lime = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	pink = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	gray = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	silver = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	cyan = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	purple = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	brown = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	green = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	red = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	black = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	totem = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	lead2 = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	nametag = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	xp = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	sea = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	scute = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	nautilus = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	phantom = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	wither = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	dragon = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	blue = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	ink = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	white = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	honeycomb = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	netherite = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	glowink = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	copper = 100
	#Percentage. Chance for the crop to grow
	#Range: 0 ~ 100
	amethyst = 100

[main]
	#Max amount of extra fruit dropped by a mature crop
	#Range: 0 ~ 100
	extraFruit = 0
	#Max amount of extra seed dropped by a mature crop
	#Range: 0 ~ 100
	extraSeed = 2
	#Ore Vein Per Chunk
	#Range: 1 ~ 100
	elematiliusOreVeinSize = 10
	#The light level emitted by the Greenhouses
	#Range: 1 ~ 15
	greenhouseLight = 9
	#How many working Accelerators you can place on top of each over
	#Range: 0 ~ 100
	acceleratorStackCount = 5
	#Amount of energy proudced by the Crop Generator. Default : 100 * Crop Tier
	#Range: 0 ~ 10000
	cropGeneratorProd = 100
	#Crop Generator : Value of the multiplier when a mature crop is harvested
	#Range: 0 ~ 100
	cropGeneratorMult = 2
	#Crop Generator : The area will be range * range. Range need to be odd
	#Range: 3 ~ 99
	cropGeneratorRange = 5
	#Harvester : The area will be range * range. Range need to be odd
	#Range: 3 ~ 99
	harvesterRange = 5
	#The capacity of the battery
	#Range: 0 ~ 1000000
	batteryCap = 1000000
	#Maximum amount of energy that can be extracted from the battery per tick
	#Range: 0 ~ 1000000
	batteryExtract = 10000

