
#Welcome to the client config file!
[gui]
	#Energy Unit rendered in machines
	#Allowed Values: REDSTONE_FLUX, FORGE_ENERGY, USELESS_ENERGY, ENERGY_UNITS, IMMERSIVE_FLUX, JOULES
	energyUnit = "FORGE_ENERGY"

[formatting]
	#How the mod name should be formatted in the tooltip. Leave blank to disable.
	#Use these formatting colors:
	#black, dark_blue, dark_green, dark_aqua, dark_red, dark_purple, gold, gray, dark_gray, blue, green, aqua, red, light_purple, yellow, white
	#With these formatting options:
	#obfuscated, bold, strikethrough, underline, italic
	modNameFormat = "blue italic"

